apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: runbooks
    files:
      - argocd/argocd-app-degraded.md
      - argocd/argocd-app-sync-failure.md
generatorOptions:
  labels:
    akuity.io/runbook: "true"